### PR TITLE
Fix set temperature from HA

### PR DESCRIPTION
**Pull request by oyvindwe**
- Allow temperature to be int
- Added tests for validations
- Run tests on GitHub
- Bump GitHub actions
- Version 1.8.1

### CODE REVIEW

**Comment by oyvindwe** [comment]
Fixes https://github.com/home-assistant/core/issues/114877

**Comment by stigvi** [comment]
I will test it tomorrow (friday) afternoon :-)

**Review by SVH-Powel — APPROVED** [review]
It is looking fine by me.

**Review by stigvi — APPROVED** [review]
And doing the review a second time with the correct username........

**Comment by stigvi** [comment]
Question: If I want to test this, how am I supposed to test a library (pynobo.py) that is not yet published to pypi.org?

**Comment by oyvindwe** [comment]
> Question: If I want to test this, how am I supposed to test a library (pynobo.py) that is not yet published to pypi.org?

It's a bit tricky. You need to change `requirements` in `homeassistant/components/nobo_hub/manifest.json` to
```
"requirements": "git+https://github.com/oyvindwe/pynobo.git@fix-set-temp#pynobo==1.8.1"
```
See [Custom requirements during development & testing](https://developers.home-assistant.io/docs/creating_integration_manifest#custom-requirements-during-development--testing)

I only do this in my development environment. I'll test HA later today before merging this PR.

**Comment by stigvi** [comment]
> I only do this in my development environment. I'll test HA later today before merging this PR.

I have a spare rpi4 with HA on....... I have tested it and had no problems changing temperature and modes. That is the two things I tested, only.

There was missing text in the config flow when it asked for the last 3 digits in the serial number. I am not sure why. It could be that I have copied the files to a custom component that something is missing.

**Comment by oyvindwe** [comment]
Works for me as well. Merging and releasing!

**Comment by oyvindwe** [comment]
> There was missing text in the config flow when it asked for the last 3 digits in the serial number.

Not missing for me. I suspect you did not copy the current translation file.

**Comment by oyvindwe** [comment]
@stigvi Please test with final version 1.8.1 as well and comment on https://github.com/home-assistant/core/pull/114982

**Comment by stigvi** [comment]
> @stigvi Please test with final version 1.8.1 as well and comment on [home-assistant/core#114982](https://github.com/home-assistant/core/pull/114982)

It's done. Looking good & working as expected.

**Pull request merged**
